<a href="https://colab.research.google.com/github/classical16/gomycode/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('/content/STEG_BILLING_HISTORY.csv')

<ipython-input-1-783ef8189dcd>:3: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/STEG_BILLING_HISTORY.csv')

In [2]:
df.head(10)

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207.0,9.0,1.0,314.0,0.0,0.0,0.0,15638.0,15952.0,8.0,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207.0,9.0,1.0,541.0,0.0,0.0,0.0,15952.0,16493.0,12.0,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207.0,9.0,1.0,585.0,0.0,0.0,0.0,16493.0,17078.0,8.0,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203.0,9.0,1.0,1200.0,186.0,0.0,0.0,7770.0,9156.0,4.0,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203.0,6.0,1.0,1082.0,0.0,0.0,0.0,9156.0,10238.0,4.0,ELEC

In [3]:
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489623,train_Client_99998,2005-08-19,10,1253571.0,0,202.0,9.0,1.0,400.0,135.0,0.0,0.0,3197.0,3732.0,8.0,ELEC
4489624,train_Client_99998,2005-12-19,10,1253571.0,0,202.0,6.0,1.0,200.0,6.0,0.0,0.0,3732.0,3938.0,4.0,ELEC
4489625,train_Client_99999,1996-09-25,11,560948.0,0,203.0,6.0,1.0,259.0,0.0,0.0,0.0,13884.0,14143.0,4.0,ELEC
4489626,train_Client_99999,1996-05-28,11,560948.0,0,203.0,6.0,1.0,603.0,0.0,0.0,0.0,13281.0,13884.0,4.0,ELEC
4489627,train_Client_99999,1996-01-25,11,560948.0,0,203.0,6.0,1.0,516.0,0.0,0.0,0.0,12765.0,13281.0,4.0,ELEC

In [4]:
client_0_bills = df.head(10)

In [5]:
client_0_bills.dtypes

client_id                object
invoice_date             object
tarif_type                int64
counter_number           object
counter_statue           object
counter_code            float64
reading_remarque        float64
counter_coefficient     float64
consommation_level_1    float64
consommation_level_2    float64
consommation_level_3    float64
consommation_level_4    float64
old_index               float64
new_index               float64
months_number           float64
counter_type             object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4489628 entries, 0 to 4489627
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             object
 1   invoice_date          object
 2   tarif_type            int64
 3   counter_number        object
 4   counter_statue        object
 5   counter_code          float64
 6   reading_remarque      float64
 7   counter_coefficient   float64
 8   consommation_level_1  float64
 9   consommation_level_2  float64
 10  consommation_level_3  float64
 11  consommation_level_4  float64
 12  old_index             float64
 13  new_index             float64
 14  months_number         float64
 15  counter_type          object
dtypes: float64(10), int64(1), object(5)
memory usage: 548.1+ MB

In [7]:
# Display the number of rows and columns
rows, columns = df.shape

print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

Number of rows: 4489628
Number of columns: 16

In [8]:
# Display the list of categorical columns and their count
categorical_columns = df.select_dtypes(include='object').columns

print(f"Number of categorical features: {len(categorical_columns)}")
print("Categorical features:", categorical_columns)

Number of categorical features: 5
Categorical features: Index(['client_id', 'invoice_date', 'counter_number', 'counter_statue',
       'counter_type'],
      dtype='object')

In [9]:
# Display the memory usage
memory_usage = df.memory_usage(deep=True).sum() / (1024**2)

print(f"Memory usage of the DataFrame: {memory_usage:.2f} MB")

Memory usage of the DataFrame: 1521.64 MB

In [10]:
# Display the count of the missing values for each columns
missing_values = df.isnull().sum()

print("Missing values per column:")
print(missing_values)

Missing values per column:
client_id                  0
invoice_date               0
tarif_type                 0
counter_number            48
counter_statue             1
counter_code               1
reading_remarque        4546
counter_coefficient        1
consommation_level_1       1
consommation_level_2       1
consommation_level_3       1
consommation_level_4       1
old_index                  1
new_index                  1
months_number              1
counter_type               1
dtype: int64

In [11]:
null_values = df["new_index"].isnull()
null_index = df[null_values].index

In [12]:
df = df.drop(null_index)

In [13]:
df.isnull().sum()

client_id                  0
invoice_date               0
tarif_type                 0
counter_number            48
counter_statue             0
counter_code               0
reading_remarque        4545
counter_coefficient        0
consommation_level_1       0
consommation_level_2       0
consommation_level_3       0
consommation_level_4       0
old_index                  0
new_index                  0
months_number              0
counter_type               0
dtype: int64

In [14]:
null_mask = df.isnull().any(axis=1)
df[null_mask]

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
615,train_Client_100012,2010-01-28,11,144686.0,0,413.0,NaN,1.0,419.0,0.0,0.0,0.0,1723.0,2142.0,12.0,ELEC
1261,train_Client_100027,2016-05-08,11,21762.0,0,413.0,NaN,1.0,169.0,0.0,0.0,0.0,17410.0,17579.0,4.0,ELEC
1301,train_Client_100028,2017-03-24,40,127333.0,0,5.0,NaN,1.0,177.0,0.0,0.0,0.0,8849.0,9026.0,4.0,GAZ
2196,train_Client_100060,2014-03-21,11,1177241.0,0,203.0,NaN,1.0,327.0,0.0,0.0,0.0,5042.0,5369.0,4.0,ELEC
2366,train_Client_100067,2018-11-15,11,964342.0,0,203.0,NaN,1.0,596.0,0.0,0.0,0.0,35114.0,35710.0,4.0,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4482180,train_Client_99807,2017-08-02,10,561179.0,0,202.0,NaN,1.0,134.0,0.0,0.0,0.0,9633.0,9767.0,4.0,ELEC
4483226,train_Client_99832,2013-06-26,11,1242722.0,0,207.0,NaN,1.0,149.0,0.0,0.0,0.0,43434.0,43583.0,2.0,ELEC
4483573,train_Client_9984,2013-04-09,11,96557.0,0,203.0,NaN,1.0,707.0,0.0,0.0,0.0,65977.0,66684.0,4.0,ELEC
4486682,train_Client_9992,2018-07-26,11,3020.0,0,203.0,NaN,1.0,2400.0,1200.0,161.0,0.0,1470.0,5231.0,12.0,ELEC
4487745,train_Client_99947,2016-09-05,40,6847056.0,0,5.0,NaN,1.0,222.0,0.0,0.0,0.0,6900.0,7122.0,4.0,GAZ

In [15]:
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489623,train_Client_99998,2005-08-19,10,1253571.0,0,202.0,9.0,1.0,400.0,135.0,0.0,0.0,3197.0,3732.0,8.0,ELEC
4489624,train_Client_99998,2005-12-19,10,1253571.0,0,202.0,6.0,1.0,200.0,6.0,0.0,0.0,3732.0,3938.0,4.0,ELEC
4489625,train_Client_99999,1996-09-25,11,560948.0,0,203.0,6.0,1.0,259.0,0.0,0.0,0.0,13884.0,14143.0,4.0,ELEC
4489626,train_Client_99999,1996-05-28,11,560948.0,0,203.0,6.0,1.0,603.0,0.0,0.0,0.0,13281.0,13884.0,4.0,ELEC
4489627,train_Client_99999,1996-01-25,11,560948.0,0,203.0,6.0,1.0,516.0,0.0,0.0,0.0,12765.0,13281.0,4.0,ELEC

In [16]:
df['reading_remarque'].fillna(df['reading_remarque'].mean(), inplace=True)

In [17]:
df.isnull().sum()

client_id                0
invoice_date             0
tarif_type               0
counter_number          48
counter_statue           0
counter_code             0
reading_remarque         0
counter_coefficient      0
consommation_level_1     0
consommation_level_2     0
consommation_level_3     0
consommation_level_4     0
old_index                0
new_index                0
months_number            0
counter_type             0
dtype: int64

In [18]:
df['counter_number']=df['counter_number'].astype(float)

In [19]:
df['counter_number'].fillna(df['counter_number'].mean(), inplace=True)

In [20]:
df.isnull().sum()

client_id               0
invoice_date            0
tarif_type              0
counter_number          0
counter_statue          0
counter_code            0
reading_remarque        0
counter_coefficient     0
consommation_level_1    0
consommation_level_2    0
consommation_level_3    0
consommation_level_4    0
old_index               0
new_index               0
months_number           0
counter_type            0
dtype: int64

In [21]:
print(df.describe())

         tarif_type  counter_number  counter_code  reading_remarque  \
count  4.489627e+06    4.489627e+06  4.489627e+06      4.489627e+06
mean   2.012683e+01    1.231981e+11  1.724852e+02      7.321663e+00
std    1.347204e+01    1.658251e+12  1.338744e+02      1.570491e+00
min    8.000000e+00    0.000000e+00  0.000000e+00      5.000000e+00
25%    1.100000e+01    1.211220e+05  5.000000e+00      6.000000e+00
50%    1.100000e+01    4.945980e+05  2.030000e+02      8.000000e+00
75%    4.000000e+01    1.115471e+06  2.070000e+02      9.000000e+00
max    4.500000e+01    2.798115e+13  6.000000e+02      4.130000e+02

       counter_coefficient  consommation_level_1  consommation_level_2  \
count         4.489627e+06          4.489627e+06          4.489627e+06
mean          1.003031e+00          4.109603e+02          1.093168e+02
std           3.079041e-01          7.577885e+02          1.219530e+03
min           0.000000e+00          0.000000e+00          0.000000e+00
25%           1.000000e+00          7.900000e+01          0.000000e+00
50%           1.000000e+00          2.740000e+02          0.000000e+00
75%           1.000000e+00          6.000000e+02          0.000000e+00
max           5.000000e+01          9.999100e+05          9.990730e+05

       consommation_level_3  consommation_level_4     old_index     new_index  \
count          4.489627e+06          4.489627e+06  4.489627e+06  4.489627e+06
mean           2.028158e+01          5.296675e+01  1.776952e+04  1.835218e+04
std            1.572874e+02          8.755661e+02  4.044315e+04  4.103072e+04
min            0.000000e+00          0.000000e+00  0.000000e+00  0.000000e+00
25%            0.000000e+00          0.000000e+00  1.791000e+03  2.057000e+03
50%            0.000000e+00          0.000000e+00  7.689000e+03  8.191000e+03
75%            0.000000e+00          0.000000e+00  2.165700e+04  2.234100e+04
max            6.449200e+04          5.479460e+05  2.800280e+06  2.870972e+06

       months_number
count   4.489627e+06
mean    4.471464e+01
std     3.123846e+03
min     0.000000e+00
25%     4.000000e+00
50%     4.000000e+00
75%     4.000000e+00
max     6.366240e+05

In [22]:
client_0_bills_boolean = df[df['client_id'] == 'train_client_0']
client_0_bills_boolean

Empty DataFrame
Columns: [client_id, invoice_date, tarif_type, counter_number, counter_statue, counter_code, reading_remarque, counter_coefficient, consommation_level_1, consommation_level_2, consommation_level_3, consommation_level_4, old_index, new_index, months_number, counter_type]
Index: []

In [23]:
client_0_bills_loc = df.loc[df['client_id'] == 'train_client_0']
client_0_bills_loc

Empty DataFrame
Columns: [client_id, invoice_date, tarif_type, counter_number, counter_statue, counter_code, reading_remarque, counter_coefficient, consommation_level_1, consommation_level_2, consommation_level_3, consommation_level_4, old_index, new_index, months_number, counter_type]
Index: []

In [24]:
# using map function
counter_type_mapping = {'ELEC': 2, 'GAZ': 1}

df['counter_type_numeric'] = df['counter_type'].map(counter_type_mapping)
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type,counter_type_numeric
0,train_Client_0,2014-03-24,11,1335667.0,0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC,2
1,train_Client_0,2013-03-29,11,1335667.0,0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC,2
2,train_Client_0,2015-03-23,11,1335667.0,0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC,2
3,train_Client_0,2015-07-13,11,1335667.0,0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC,2
4,train_Client_0,2016-11-17,11,1335667.0,0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489623,train_Client_99998,2005-08-19,10,1253571.0,0,202.0,9.0,1.0,400.0,135.0,0.0,0.0,3197.0,3732.0,8.0,ELEC,2
4489624,train_Client_99998,2005-12-19,10,1253571.0,0,202.0,6.0,1.0,200.0,6.0,0.0,0.0,3732.0,3938.0,4.0,ELEC,2
4489625,train_Client_99999,1996-09-25,11,560948.0,0,203.0,6.0,1.0,259.0,0.0,0.0,0.0,13884.0,14143.0,4.0,ELEC,2
4489626,train_Client_99999,1996-05-28,11,560948.0,0,203.0,6.0,1.0,603.0,0.0,0.0,0.0,13281.0,13884.0,4.0,ELEC,2
4489627,train_Client_99999,1996-01-25,11,560948.0,0,203.0,6.0,1.0,516.0,0.0,0.0,0.0,12765.0,13281.0,4.0,ELEC,2

In [25]:
df.drop('counter_statue', axis=1, inplace=True)
df

,client_id,invoice_date,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type,counter_type_numeric
0,train_Client_0,2014-03-24,11,1335667.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC,2
1,train_Client_0,2013-03-29,11,1335667.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC,2
2,train_Client_0,2015-03-23,11,1335667.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC,2
3,train_Client_0,2015-07-13,11,1335667.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC,2
4,train_Client_0,2016-11-17,11,1335667.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489623,train_Client_99998,2005-08-19,10,1253571.0,202.0,9.0,1.0,400.0,135.0,0.0,0.0,3197.0,3732.0,8.0,ELEC,2
4489624,train_Client_99998,2005-12-19,10,1253571.0,202.0,6.0,1.0,200.0,6.0,0.0,0.0,3732.0,3938.0,4.0,ELEC,2
4489625,train_Client_99999,1996-09-25,11,560948.0,203.0,6.0,1.0,259.0,0.0,0.0,0.0,13884.0,14143.0,4.0,ELEC,2
4489626,train_Client_99999,1996-05-28,11,560948.0,203.0,6.0,1.0,603.0,0.0,0.0,0.0,13281.0,13884.0,4.0,ELEC,2
4489627,train_Client_99999,1996-01-25,11,560948.0,203.0,6.0,1.0,516.0,0.0,0.0,0.0,12765.0,13281.0,4.0,ELEC,2