<a href="https://colab.research.google.com/github/classical16/gomycode/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

df = pd.read_csv('/content/STEG_BILLING_HISTORY.csv')

In [8]:
df.head(10)

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11.0,1335667.0,0.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11.0,1335667.0,0.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11.0,1335667.0,0.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11.0,1335667.0,0.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11.0,1335667.0,0.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
5,train_Client_0,2017-07-17,11.0,1335667.0,0.0,207.0,9.0,1.0,314.0,0.0,0.0,0.0,15638.0,15952.0,8.0,ELEC
6,train_Client_0,2018-12-07,11.0,1335667.0,0.0,207.0,9.0,1.0,541.0,0.0,0.0,0.0,15952.0,16493.0,12.0,ELEC
7,train_Client_0,2019-03-19,11.0,1335667.0,0.0,207.0,9.0,1.0,585.0,0.0,0.0,0.0,16493.0,17078.0,8.0,ELEC
8,train_Client_0,2011-07-22,11.0,1335667.0,0.0,203.0,9.0,1.0,1200.0,186.0,0.0,0.0,7770.0,9156.0,4.0,ELEC
9,train_Client_0,2011-11-22,11.0,1335667.0,0.0,203.0,6.0,1.0,1082.0,0.0,0.0,0.0,9156.0,10238.0,4.0,ELEC

In [9]:
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11.0,1335667.0,0.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11.0,1335667.0,0.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11.0,1335667.0,0.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11.0,1335667.0,0.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11.0,1335667.0,0.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38652,train_Client_10104,2016-02-08,11.0,926466.0,0.0,203.0,9.0,1.0,770.0,0.0,0.0,0.0,26152.0,26922.0,6.0,ELEC
38653,train_Client_10104,2016-11-29,11.0,926466.0,0.0,203.0,9.0,1.0,800.0,83.0,0.0,0.0,26922.0,27805.0,4.0,ELEC
38654,train_Client_10104,2018-07-24,11.0,926466.0,0.0,203.0,9.0,1.0,733.0,0.0,0.0,0.0,30337.0,31070.0,4.0,ELEC
38655,train_Client_10104,2017-03-29,11.0,926466.0,0.0,203.0,9.0,1.0,424.0,0.0,0.0,0.0,27805.0,28229.0,4.0,ELEC
38656,train_Client_10104,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
client_0_bills = df.head(10)

In [12]:
client_0_bills.dtypes

client_id                object
invoice_date             object
tarif_type              float64
counter_number          float64
counter_statue          float64
counter_code            float64
reading_remarque        float64
counter_coefficient     float64
consommation_level_1    float64
consommation_level_2    float64
consommation_level_3    float64
consommation_level_4    float64
old_index               float64
new_index               float64
months_number           float64
counter_type             object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38657 entries, 0 to 38656
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   client_id             38657 non-null  object
 1   invoice_date          38657 non-null  object
 2   tarif_type            38656 non-null  float64
 3   counter_number        38655 non-null  float64
 4   counter_statue        38656 non-null  float64
 5   counter_code          38656 non-null  float64
 6   reading_remarque      38622 non-null  float64
 7   counter_coefficient   38656 non-null  float64
 8   consommation_level_1  38656 non-null  float64
 9   consommation_level_2  38656 non-null  float64
 10  consommation_level_3  38656 non-null  float64
 11  consommation_level_4  38656 non-null  float64
 12  old_index             38656 non-null  float64
 13  new_index             38656 non-null  float64
 14  months_number         38656 non-null  float64
 15  counter_type          38656 non-null  object
dtypes: float64(13), object(3)
memory usage: 4.7+ MB

In [13]:
# Display the number of rows and columns
rows, columns = df.shape

print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

Number of rows: 38657
Number of columns: 16

In [14]:
# Display the list of categorical columns and their count
categorical_columns = df.select_dtypes(include='object').columns

print(f"Number of categorical features: {len(categorical_columns)}")
print("Categorical features:", categorical_columns)

Number of categorical features: 3
Categorical features: Index(['client_id', 'invoice_date', 'counter_type'], dtype='object')

In [15]:
# Display the memory usage
memory_usage = df.memory_usage(deep=True).sum() / (1024**2)

print(f"Memory usage of the DataFrame: {memory_usage:.2f} MB")

Memory usage of the DataFrame: 11.34 MB

In [16]:
# Display the count of the missing values for each columns
missing_values = df.isnull().sum()

print("Missing values per column:")
print(missing_values)

Missing values per column:
client_id                0
invoice_date             0
tarif_type               1
counter_number           2
counter_statue           1
counter_code             1
reading_remarque        35
counter_coefficient      1
consommation_level_1     1
consommation_level_2     1
consommation_level_3     1
consommation_level_4     1
old_index                1
new_index                1
months_number            1
counter_type             1
dtype: int64

In [17]:
null_values = df["new_index"].isnull()
df[null_values].index

Int64Index([38656], dtype='int64')

In [20]:
df = df.drop(38656)

In [21]:
df.isnull().sum()

client_id                0
invoice_date             0
tarif_type               0
counter_number           1
counter_statue           0
counter_code             0
reading_remarque        34
counter_coefficient      0
consommation_level_1     0
consommation_level_2     0
consommation_level_3     0
consommation_level_4     0
old_index                0
new_index                0
months_number            0
counter_type             0
dtype: int64

In [22]:
null_mask = df.isnull().any(axis=1)
df[null_mask]

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
615,train_Client_100012,2010-01-28,11.0,1.446860e+05,0.0,413.0,NaN,1.0,419.0,0.0,0.0,0.0,1723.0,2142.0,12.0,ELEC
1261,train_Client_100027,2016-05-08,11.0,2.176200e+04,0.0,413.0,NaN,1.0,169.0,0.0,0.0,0.0,17410.0,17579.0,4.0,ELEC
1301,train_Client_100028,2017-03-24,40.0,1.273330e+05,0.0,5.0,NaN,1.0,177.0,0.0,0.0,0.0,8849.0,9026.0,4.0,GAZ
2196,train_Client_100060,2014-03-21,11.0,1.177241e+06,0.0,203.0,NaN,1.0,327.0,0.0,0.0,0.0,5042.0,5369.0,4.0,ELEC
2366,train_Client_100067,2018-11-15,11.0,9.643420e+05,0.0,203.0,NaN,1.0,596.0,0.0,0.0,0.0,35114.0,35710.0,4.0,ELEC
2995,train_Client_100083,2007-11-14,40.0,6.788434e+06,0.0,5.0,NaN,1.0,77.0,0.0,0.0,0.0,489.0,566.0,4.0,GAZ
4037,train_Client_100113,2011-06-07,11.0,6.089040e+05,0.0,203.0,NaN,1.0,876.0,0.0,0.0,0.0,13554.0,14430.0,4.0,ELEC
5130,train_Client_100140,2018-04-17,11.0,2.175702e+12,0.0,203.0,NaN,1.0,352.0,0.0,0.0,0.0,130.0,482.0,4.0,ELEC
7106,train_Client_10020,2010-10-18,40.0,1.636400e+05,0.0,5.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,GAZ
10071,train_Client_100278,2009-09-10,40.0,4.532200e+04,0.0,5.0,NaN,1.0,94.0,0.0,0.0,0.0,2442.0,2536.0,4.0,GAZ
10138,train_Client_100278,2013-02-14,11.0,5.237520e+05,0.0,207.0,NaN,1.0,1125.0,0.0,0.0,0.0,17040.0,18165.0,4.0,ELEC
10227,train_Client_100280,2017-02-23,11.0,1.158460e+06,0.0,203.0,NaN,1.0,1123.0,0.0,0.0,0.0,16301.0,17424.0,8.0,ELEC
10946,train_Client_100303,2018-05-06,40.0,4.359410e+05,0.0,5.0,NaN,1.0,76.0,0.0,0.0,0.0,1451.0,1527.0,4.0,GAZ
12798,train_Client_100346,2007-11-07,11.0,1.035779e+06,0.0,203.0,NaN,1.0,124.0,0.0,0.0,0.0,150.0,274.0,4.0,ELEC
16792,train_Client_10045,2018-06-19,40.0,4.164666e+06,0.0,5.0,NaN,1.0,92.0,0.0,0.0,0.0,351.0,443.0,4.0,GAZ
17865,train_Client_100481,2017-12-09,40.0,3.038800e+04,0.0,5.0,NaN,1.0,250.0,0.0,0.0,0.0,5920.0,6170.0,8.0,GAZ
18025,train_Client_100485,2009-10-12,11.0,9.097050e+05,0.0,203.0,NaN,1.0,439.0,0.0,0.0,0.0,2715.0,3154.0,4.0,ELEC
19963,train_Client_100544,2014-12-24,15.0,4.861200e+04,0.0,202.0,NaN,1.0,346.0,0.0,0.0,0.0,19408.0,19754.0,4.0,ELEC
21379,train_Client_100587,2016-04-10,11.0,9.242610e+05,0.0,207.0,NaN,1.0,60.0,0.0,0.0,0.0,30180.0,30240.0,2.0,ELEC
23062,train_Client_100634,2017-05-07,40.0,6.981763e+06,0.0,5.0,NaN,1.0,55.0,0.0,0.0,0.0,641.0,696.0,4.0,GAZ
24949,train_Client_100692,2019-03-22,11.0,NaN,0.0,203.0,9.0,1.0,185.0,0.0,0.0,0.0,6918.0,7103.0,4.0,ELEC
25187,train_Client_100698,2015-10-02,40.0,2.102490e+05,0.0,5.0,NaN,1.0,8.0,0.0,0.0,0.0,140.0,148.0,4.0,GAZ
25778,train_Client_100714,2011-12-13,11.0,1.734380e+05,0.0,420.0,NaN,1.0,1200.0,857.0,0.0,0.0,4971.0,7028.0,4.0,ELEC
25845,train_Client_100717,2015-02-17,40.0,9.432560e+07,0.0,10.0,NaN,1.0,175.0,0.0,0.0,0.0,15203.0,15378.0,2.0,GAZ
25943,train_Client_100719,2017-05-09,11.0,2.670000e+02,0.0,207.0,NaN,1.0,618.0,0.0,0.0,0.0,14487.0,15105.0,4.0,ELEC
27045,train_Client_100750,2018-02-23,11.0,7.251670e+05,0.0,207.0,NaN,1.0,616.0,0.0,0.0,0.0,33718.0,34334.0,12.0,ELEC
27150,train_Client_100753,2013-09-10,15.0,4.984180e+05,0.0,202.0,NaN,1.0,0.0,0.0,0.0,0.0,1127.0,1127.0,4.0,ELEC
28421,train_Client_100780,2016-09-16,11.0,6.253000e+04,0.0,203.0,NaN,1.0,380.0,0.0,0.0,0.0,20974.0,21354.0,4.0,ELEC
32234,train_Client_100888,2007-06-08,11.0,5.708810e+05,0.0,203.0,NaN,1.0,278.0,0.0,0.0,0.0,5540.0,5818.0,4.0,ELEC
32495,train_Client_100898,2010-07-16,11.0,1.113567e+06,0.0,203.0,NaN,1.0,265.0,0.0,0.0,0.0,2536.0,2801.0,4.0,ELEC
33707,train_Client_100922,2017-11-17,11.0,1.515550e+05,0.0,413.0,NaN,1.0,50.0,0.0,0.0,0.0,4618.0,4668.0,4.0,ELEC
33844,train_Client_100928,2014-01-08,11.0,1.211431e+06,0.0,203.0,NaN,1.0,389.0,0.0,0.0,0.0,6054.0,6443.0,4.0,ELEC
36624,train_Client_100991,2018-05-30,40.0,4.861580e+06,0.0,5.0,NaN,1.0,50.0,0.0,0.0,0.0,374.0,424.0,4.0,GAZ
37585,train_Client_101012,2013-07-29,40.0,6.982022e+06,0.0,5.0,NaN,1.0,240.0,0.0,0.0,0.0,3537.0,3777.0,4.0,GAZ
37996,train_Client_101025,2006-05-24,15.0,8.767910e+05,0.0,202.0,NaN,1.0,0.0,0.0,0.0,0.0,24446.0,24446.0,4.0,ELEC

In [24]:
df

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11.0,1335667.0,0.0,203.0,8.0,1.0,82.0,0.0,0.0,0.0,14302.0,14384.0,4.0,ELEC
1,train_Client_0,2013-03-29,11.0,1335667.0,0.0,203.0,6.0,1.0,1200.0,184.0,0.0,0.0,12294.0,13678.0,4.0,ELEC
2,train_Client_0,2015-03-23,11.0,1335667.0,0.0,203.0,8.0,1.0,123.0,0.0,0.0,0.0,14624.0,14747.0,4.0,ELEC
3,train_Client_0,2015-07-13,11.0,1335667.0,0.0,207.0,8.0,1.0,102.0,0.0,0.0,0.0,14747.0,14849.0,4.0,ELEC
4,train_Client_0,2016-11-17,11.0,1335667.0,0.0,207.0,9.0,1.0,572.0,0.0,0.0,0.0,15066.0,15638.0,12.0,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38651,train_Client_101039,2012-03-26,11.0,513600.0,0.0,207.0,8.0,1.0,625.0,0.0,0.0,0.0,10961.0,11586.0,8.0,ELEC
38652,train_Client_10104,2016-02-08,11.0,926466.0,0.0,203.0,9.0,1.0,770.0,0.0,0.0,0.0,26152.0,26922.0,6.0,ELEC
38653,train_Client_10104,2016-11-29,11.0,926466.0,0.0,203.0,9.0,1.0,800.0,83.0,0.0,0.0,26922.0,27805.0,4.0,ELEC
38654,train_Client_10104,2018-07-24,11.0,926466.0,0.0,203.0,9.0,1.0,733.0,0.0,0.0,0.0,30337.0,31070.0,4.0,ELEC
38655,train_Client_10104,2017-03-29,11.0,926466.0,0.0,203.0,9.0,1.0,424.0,0.0,0.0,0.0,27805.0,28229.0,4.0,ELEC

In [28]:
df['reading_remarque'].fillna(df['reading_remarque'].mean(), inplace=True)

In [29]:
df.isnull().sum()

client_id               0
invoice_date            0
tarif_type              0
counter_number          1
counter_statue          0
counter_code            0
reading_remarque        0
counter_coefficient     0
consommation_level_1    0
consommation_level_2    0
consommation_level_3    0
consommation_level_4    0
old_index               0
new_index               0
months_number           0
counter_type            0
dtype: int64

In [30]:
df['counter_number'].fillna(df['counter_number'].mean(), inplace=True)

In [31]:
df.isnull().sum()

client_id               0
invoice_date            0
tarif_type              0
counter_number          0
counter_statue          0
counter_code            0
reading_remarque        0
counter_coefficient     0
consommation_level_1    0
consommation_level_2    0
consommation_level_3    0
consommation_level_4    0
old_index               0
new_index               0
months_number           0
counter_type            0
dtype: int64

In [34]:
print(df.describe())

         tarif_type  counter_number  counter_statue  counter_code  \
count  38656.000000    3.865600e+04    38656.000000  38656.000000
mean      20.195312    8.294626e+10        0.040744    168.926557
std       13.505675    1.351370e+12        0.362690    130.604250
min        9.000000    0.000000e+00        0.000000      5.000000
25%       11.000000    1.296020e+05        0.000000      5.000000
50%       11.000000    4.945610e+05        0.000000    203.000000
75%       40.000000    1.158448e+06        0.000000    207.000000
max       45.000000    2.718115e+13        5.000000    506.000000

       reading_remarque  counter_coefficient  consommation_level_1  \
count      38656.000000              38656.0          38656.000000
mean           7.314639                  1.0            407.010425
std            1.355391                  0.0            499.456031
min            6.000000                  1.0              0.000000
25%            6.000000                  1.0             76.000000
50%            8.000000                  1.0            267.000000
75%            9.000000                  1.0            600.000000
max            9.000000                  1.0          13544.000000

       consommation_level_2  consommation_level_3  consommation_level_4  \
count          38656.000000          38656.000000          38656.000000
mean              82.905784             26.654646             36.821477
std              766.281169            543.433644            635.057885
min                0.000000              0.000000              0.000000
25%                0.000000              0.000000              0.000000
50%                0.000000              0.000000              0.000000
75%                0.000000              0.000000              0.000000
max            99398.000000          45360.000000          67139.000000

           old_index      new_index  months_number
count   38656.000000   38656.000000   38656.000000
mean    15960.810249   16490.551531      15.959722
std     29116.859269   29482.271016     825.441322
min         0.000000       0.000000       1.000000
25%      1691.000000    1977.000000       4.000000
50%      7032.500000    7529.500000       4.000000
75%     20497.500000   21191.000000       4.000000
max    465218.000000  470698.000000   99104.000000

In [35]:
client_0_bills_boolean = df[df['client_id'] == 'train_client_0']

In [36]:
client_0_bills_loc = df.loc[df['client_id'] == 'train_client_0']

In [37]:
# using map function
counter_type_mapping = {'ELEC': 2, 'GAZ': 1}

df['counter_type_numeric'] = df['counter_type'].map(counter_type_mapping)

In [39]:
df.drop('counter_statue', axis=1, inplace=True)